# Generated by Django 4.1.2 on 2022-10-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn13',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='book',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ratings_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='text_review_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='Branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='City',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Customer_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Gender',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Payment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Product_line',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Rating',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Unitprice',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cogs',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='groosmarginpercent',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='grossincome',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='invoiceid',
            field=models.IntegerField(null=True),
        ),
    ]
