# Generated by Django 4.1.2 on 2022-10-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_authors_remove_book_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='invoiceid',
            new_name='InvoiceID',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Unitprice',
            new_name='Unit_price',
        ),
    ]
