# Generated by Django 4.1.2 on 2022-10-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_invoiceid_book_invoiceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='InvoiceID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
