# Generated by Django 4.1.2 on 2022-10-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='groosmarginpercent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='grossincome',
            field=models.FloatField(null=True),
        ),
    ]
