# Generated by Django 4.1.2 on 2022-10-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_monthlygrossincome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlygrossincome',
            old_name='grossincome',
            new_name='highestgrossincome',
        ),
    ]
